CMplay/CMplay/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mymusic/', include('MyMusic.urls')),
    url(r'^',include('MyMusic.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CMplay/MyMusic/urls.py
from django.conf.urls import url
from . import views

#namespace
app_name = 'MyMusic'

#url's registradas con sus respetivas vistas ,

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^cancionadd/$', views.nueva_cancion, name='cancion-add'),
    url(r'^listas/$', views.listas_view, name='listas'),
    url(r'^nueva_lista/$', views.nueva_lista, name='lista-add'),
    #direccion dinamica , depende de la id de la lista
    url(r'^(?P<lista_id>[0-9]+)/borrar_lista/$', views.borrar_lista, name='eliminar_lista'),
    url(r'^(?P<lista_id>[0-9]+)/datalles/$', views.detail_lista, name='lista_detallada'),
    url(r'^(?P<cancion_id>[0-9]+)/borrar_cancion/$', views.borar_cancion, name='eliminar_cancion'),
    url(r'^(?P<ratin>[0-9]+)/(?P<cancion_id>[0-9]+)/$', views.calificar, name='ratin_cancion'),
    url(r'^(?P<lista_id>[0-9]+)/borrar/(?P<cancion_id>[0-9]+)/$', views.borrar_cancio_lista, name='borrar_cancion_lista'),
    url(r'^(?P<lista_id>[0-9]+)/$', views.editar_lista, name='editar_list'),

    #en edicion
    url(r'^(?P<count_id>[0-9]+)/(?P<cantidad>[0-9]+)/(?P<urlcancion>\d+)/$', views.reproductor, name='reproduce'),
   # url(r'^(?P<count_id>[0-9]+)/reproducir/(?P<url_cancion>[a-zA_Z]+)/(?P<cantidad>[0-9]+)/$', views.reproductor, name='reproduce'),

    #url(r'^(?P<ratin>[c0-9]+)/(?P<cancion_act>[a-zA_Z]+)/$',views.calificar,name='ratin_cancion'),


]

CMplay/MyMusic/models.py
from django.db import models
from django.contrib.auth.models import Permission, User

# Create your models here.

class Cancion(models.Model):
    #muchas canciones pueden pertenecer a un usuario ManyToOne
    user = models.ForeignKey(User, default=1)
    titulo_cancion=models.CharField(max_length=500)
    artista = models.CharField(max_length=250)
    audio = models.FileField(default='')

    def __str__(self):
        return self.titulo_cancion

class Lista(models.Model):
    user_list = models.ForeignKey(User, default=User)
    titulo_de_lista=models.CharField(max_length=500)

    #un lista puede tener muchas canciones, y una canciones puede pertenecer a varias listas
    canciones = models.ManyToManyField(Cancion,blank=True)

    def __str__(self):
        return self.titulo_de_lista

class Calificacion(models.Model):
    user_calificador=models.CharField(max_length=30)
    rating=models.IntegerField(default=0)
    rating_s=models.CharField(max_length=6)
    fue_calificado=models.BooleanField(default=False)
    #una canción puede tener muchas calificaciones
    cancion_calificada=models.ForeignKey(Cancion)

    def __int__(self):
        return self.rating

CMplay/MyMusic/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Cancion, Lista


#Formularios
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        labels={'username':'Nombre de Usuario','password':'contraseña'}

class CancionForm(forms.ModelForm):

    class Meta:
        model = Cancion
        fields = ['titulo_cancion', 'artista',  'audio']
        labels={'titulo_cancion':'Titulo de la Canción'}



class ListaForm(forms.ModelForm):

    #definimos un atributo de entrada extra , editando la clase
    def __init__(self,user, *args, **kwargs):
        super(ListaForm, self).__init__(*args, **kwargs)
        self.fields['canciones'] = forms.ModelMultipleChoiceField(queryset=Cancion.objects.filter(user=user)
                                                                  ,required=False,widget=forms.CheckboxSelectMultiple)
    class Meta:
        model = Lista
        fields = ['titulo_de_lista','canciones']

CMplay/MyMusic/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.http import JsonResponse
from django.db.models import Q
from django.shortcuts import render,get_object_or_404,redirect
from .forms import UserForm,CancionForm,ListaForm
from .models import Cancion,Lista,Calificacion
from .funciones import *
from django.core.mail import EmailMultiAlternatives

#extensiones permitidas para archivos de audio
AUDIO_EXT = ['wav', 'mp3']


#vista de formulario añadir cancion
def nueva_cancion(request):

    #si el usuario se ha logeado.  lo devuelve a paina de inicio
    if not request.user.is_authenticated():
        return render(request, 'MyMusic/login_form.html')
    else:
        #recuperamos información del formulario puesnto el la pagina html
        form = CancionForm(request.POST or None, request.FILES or None)

        if form.is_valid():
            #guardamos el formulario en una variable indicando que aun no terminamos de gestionar los datos
            cancion = form.save(commit=False)
            cancion.user = request.user

            cancion.audio = request.FILES['audio']

            #recuperamos el archivo y guardamos su extensión
            file_type = cancion.audio.url.split('.')[-1]
            file_type = file_type.lower()
            canciones = Cancion.objects.filter(user=request.user)

            if file_type not in AUDIO_EXT:
                context = {
                    'form': form,
                    'error_message': 'El archivo debe ser MP3 o WAV',
                }
                #enviamos de vuelta a la pagina cn un mensaje
                return render(request, 'MyMusic/cancion_form.html', context)
            cancion.save()
            context = {
                'canciones': canciones,
                'username': request.user.username
            }
            return render(request, 'MyMusic/index.html', context)
        context = {
            "form": form,
            'error_message': 'Error en Formulario',
        }
        return render(request, 'MyMusic/cancion_form.html', context)

#vista nueva lista
def nueva_lista(request):

    if not request.user.is_authenticated():
        return render(request, 'MyMusic/login_form.html')
    else:

        #form=ListaForm(request.POST or None, request.FILES or None)
        form = ListaForm(request.user,request.POST or None, request.FILES or None)

        if form.is_valid():
            lista = form.save(commit=False)
            lista.user_list = request.user
            lista.save()

            #añadimos las  canciones,
            lista.canciones = form.cleaned_data['canciones']

            context = {
                'username': request.user.username,
                'lista': lista,
            }
            return render(request,'MyMusic/lista_detail.html',context)
            #return redirect('/')
        context={
            'form':form,
            'error_message': 'Error ',
        }
        return render(request,'MyMusic/lista_form.html',context)

def editar_lista(request, lista_id):
    lista=get_object_or_404(Lista, pk=lista_id)
    context={}
    if request.method == "POST":
        form = ListaForm(request.user,request.POST, instance=lista)
        if form.is_valid():
            lista = form.save(commit=False)
            lista.user_list = request.user
            lista.save()

            #añadimos las  canciones,
            lista.canciones = form.cleaned_data['canciones']

            context = {
                'username': request.user.username,
                'lista': lista,
            }
            return render(request,'MyMusic/lista_detail.html',context)
    else:
        form = ListaForm(request.user,instance=lista)
        context={
            'form':form,
            'error_message': 'Error ',
        }
    return render(request,'MyMusic/lista_form.html',context)

def listas_view(request):

    if not request.user.is_authenticated():
        return render(request, 'MyMusic/login_form.html')
    else:

        canciones_user = Cancion.objects.filter(user=request.user)
        listas_user=Lista.objects.filter(user_list=request.user)
        context = {
            'canciones': canciones_user,
            'username': request.user.username,
            'listas':listas_user,
        }
        return render(request, 'MyMusic/listas.html', context)



# Create your views here.
def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'MyMusic/login_form.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                canciones = Cancion.objects.filter(user=request.user)
                context={
                    'canciones': canciones,
                     'username': username
                         }
                return render(request, 'MyMusic/index.html',context )
            else:
                return render(request, 'MyMusic/login_form.html', {'error_message': 'Su cuenta ha sido deshabilitada'})
        else:
            return render(request, 'MyMusic/login_form.html', {'error_message': 'El usuario no existe'})
    return render(request, 'MyMusic/login_form.html')


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                canciones = Cancion.objects.filter(user=request.user)
                context={
                    'canciones': canciones,
                     'username': username
                         }
                return render(request, 'MyMusic/index.html', context)
    context = {
        "form": form,
    }
    return render(request, 'MyMusic/registration_form.html', context)

def index(request):
    if not request.user.is_authenticated():
        return render(request, 'MyMusic/login_form.html')
    else:
        #canciones = Cancion.objects.filter(user=request.user)
        canciones=Cancion.objects.all()
        canciones_user=Cancion.objects.filter(user=request.user)

        #song_results = Song.objects.all()
        query = request.GET.get("q")
        if query:
            canciones = canciones.filter(Q(titulo_cancion__icontains=query) |  Q(artista__icontains=query)).distinct()
            """
            song_results = song_results.filter(
                Q(song_title__icontains=query)
            ).distinct()
            """
            context={
                'canciones': canciones,
                'username': request.user.username,
            }
            return render(request, 'MyMusic/index.html', context)
        else:
            return render(request, 'MyMusic/index.html', {'canciones': canciones_user, 'username': request.user.username})


def borar_cancion(request,cancion_id):
    cancion=Cancion.objects.get(pk=cancion_id)
    califica_cancion=cancion.calificacion_set.all()
    cancion.delete()
    califica_cancion.delete()
    canciones = Cancion.objects.filter(user=request.user)

    context = {
        'canciones': canciones,
        'username': request.user.username,
    }
    return render(request, 'MyMusic/index.html', context)

def borrar_lista(request, lista_id):
    canciones_user = Cancion.objects.filter(user=request.user)
    lista=Lista.objects.get(pk=lista_id)
    lista.delete()
    listas_user=Lista.objects.filter(user_list=request.user)
    context = {
        'canciones': canciones_user,
        'username': request.user.username,
        'listas':listas_user,
    }
    return render(request, 'MyMusic/listas.html', context)

def borrar_cancio_lista(request,lista_id,cancion_id):
    cancion=Cancion.objects.get(pk=cancion_id)
    lista=Lista.objects.get(pk=lista_id)
    #cancion.lista_set.remove(lista)
    lista.canciones.remove(cancion)
    context = {
        'username': request.user.username,
        'lista':lista,
    }
    return render(request, 'MyMusic/lista_detail.html', context)


def detail_lista(request, lista_id):
    lista=Lista.objects.get(pk=lista_id)
    context = {
        'username': request.user.username,
        'lista':lista,
    }
    return render(request, 'MyMusic/lista_detail.html', context)

def reproductor(request, count_id,cantidad,urlcancion):
    context={
        'success':True,
        'tag_id': count_id,
        'url_c':urlcancion,
        'tam':cantidad,
    }
    return JsonResponse(context)


def calificar(request,ratin, cancion_id):

    try:
        cancion=Cancion.objects.get(pk=cancion_id)
        calificaciones=cancion.calificacion_set.all()                 # obtenemos todas las calificaciones de la canción
        for cancion_cal in calificaciones:                          #buscamos si la cancion fue calificada por este usuario
            if cancion_cal.user_calificador==request.user.username:
                print ("la cancion ya fue calificada")
                return JsonResponse({'success': False})

        ratin_s=StringNum(ratin)
        calificacion = Calificacion(user_calificador=request.user.username,
                                    rating=ratin,rating_s=ratin_s, fue_calificado=True,
                                    cancion_calificada=cancion)
        calificacion.save()

        """
        envio de email
        enviamos email si calificamos una cancion que no sea del usuario actual.
        """
        if cancion.user.username!=request.user.username:

CMplay/MyMusic/templates/MyMusic/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-3">
            {{ field.label_tag }}
        </label>
        <div class="col-sm-15 col-sm-9 ">
            {{ field }}
        </div>
    </div>
{% endfor %}
{% if error_massage %}
    <p class="text-center"><strong> {{ error_massage }}</strong> </p>
{% endif %}

CMplay/MyMusic/templates/MyMusic/index.html
<!-- cargar los patch a su staticos
-->
<title>
    CMPlayList
</title>


{% extends 'MyMusic/plantilla.html' %}
{% block canciones_active %}active{% endblock %}

{% block body %}
<div class="container-fluid canciones-container">
    <div class="row">
        <div >

            <div class="center-block">
                <ul class="nav text-center" style="margin-bottom: 10px;">
                    <li role="presentation" ><a> <h2 style="font-family: 'Kaushan Script', cursive; text-transform: uppercase;">{{ username }}</h2> </a></li>
                </ul>
            </div>

            {% if canciones %}
            <div class="panel panel-default">
                <div class="panel-body">

                   <h2 class="text-center" style="text-transform: capitalize">canciones</h2>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Artista</th>
                            <th>Archivo de audio</th>
                            <th>Calificacion</th>
                            <th>Subido por</th>
                            <th>Acciones</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for song in canciones %}
                            {% with cali=song.calificacion_set.filter user_calificador=username %}
                            <tr>
                                <td style="text-transform: capitalize"> &nbsp;&nbsp;{{ song.titulo_cancion }}</td>
                                <td style="text-transform: capitalize">&nbsp;&nbsp;{{ song.artista }}</td>
                                <td>&nbsp;&nbsp;&nbsp;
                                    <a target="_blank" href="{{ song.audio.url }}">
                                        <button type="button" class="btn btn-success btn-xs ">
                                               <span class="glyphicon glyphicon-play">&nbsp;</span>Play
                                        </button>
                                     </a>

                                </td>
                                <td>
                                    {% if cali %}
                                         <abbr title="Gracias por calificar">

                                         {% for elem in cali%}
                                             {% for i in elem.rating_s %}
                                                 <span class="glyphicon glyphicon-star"></span>
                                             {% endfor %}
                                         {% endfor %}
                                         </abbr>
                                    {% else %}
                                        <div>  </div>
                                        <abbr title="Califica esta canción" id="cancion{{ song.id }}">
                                        {% for i in "cinco" %}
                                           <a href="{% url 'MyMusic:ratin_cancion' forloop.counter song.id %}" class="btn-canciones" >
                                               <span class="glyphicon glyphicon-star-empty"> </span>
                                           </a>
                                        {% endfor %}
                                        </abbr>
                                    {% endif %}

                                </td>
                                <td>
                                   &nbsp;&nbsp; <span class="text-success">{{ song.user.username }}</span>

                                </td>
                                <td>
                                    {% if song.user.username == username %}
                                    <form action="{% url 'MyMusic:eliminar_cancion' song.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                                        <abbr title="Eliminar Canción">
                                            <button type="submit" class="btn btn-danger btn-xs   ">
                                                <span class="glyphicon glyphicon-remove"> </span>&nbsp; Eliminar
                                            </button>
                                        </abbr>
                                    </form>
                                    {% endif %}
                                </td>
                            </tr>
                            {% endwith %}
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>
        {% else %}
            <div class="col-centered">
                <h3>No se encontraron canciónes </h3>
            </div>
        {% endif %}
            <div class="col-centered">

                <a href="{% url 'MyMusic:cancion-add' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Añadir Canción
                    </button>
                </a>
            </div>
        </div>
    </div>

</div>

{% endblock %}

CMplay/MyMusic/templates/MyMusic/lista_detail.html
<!-- cargar los patch a su staticos
-->
<title>
    CMPlaylist-Detalles Lista
</title>

{% extends 'MyMusic/plantilla.html' %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="center-block">
                <ul class="nav text-center" style="margin-bottom: 10px;">
                    <li role="presentation" ><a> <h2 style="font-family: 'Kaushan Script', cursive; text-transform: uppercase;">{{ username }}</h2> </a></li>

                </ul>
            </div>
            <div class="panel panel-collapse ">
                <div class="panel-default">
                   <h2 class="text-center" style="text-transform: capitalize"> {{ lista.titulo_de_lista }}</h2>

                    <div class="text-center">
                        <audio src="" controls id="audioPlayer" >
                            Lo sentimos tu navegador no soporta el reproductor de audio
                        </audio>
                    </div>
                    <table class="table">
                        <thead>
                            <tr>
                                <th style="text-transform: capitalize">Nombre</th>
                                <th hstyle="text-transform: capitalize">Artista</th>
                                <th>Archivo de audio</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody id="list_can">
                        {% for cancion in lista.canciones.all %}

                            <tr >
                                <td style="text-transform: capitalize"> &nbsp;&nbsp;{{ cancion.titulo_cancion }}</td>
                                <td style="text-transform: capitalize">&nbsp;&nbsp;{{ cancion.artista }}</td>
                                <td id="boplay" class="tdcan">&nbsp;&nbsp;&nbsp;&nbsp;
                                    <a  href="{{ cancion.audio.url }} " id="can{{ forloop.counter }}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play">&nbsp;</span>Play
                                        </button>
                                    </a>
                                </td>

                                <td>

                                    <a href="{% url 'MyMusic:borrar_cancion_lista' lista.id cancion.id %}">
                                        <abbr title="Eliminar Canción">
                                            <button type="submit" class="btn btn-danger btn-xs   ">
                                                <span class="glyphicon glyphicon-remove"> </span>&nbsp; Eliminar
                                            </button>
                                        </abbr>
                                    </a>

                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
                    <div class="col-centered">
                        <a href="{% url 'MyMusic:editar_list' lista.id %}">
                            <button type="button" class="btn btn-success">
                                <span class="glyphicon glyphicon-pencil"></span>&nbsp;Añadir/Editar lista
                            </button>
                        </a>
                    </div>
            </div>
        </div>
    </div>

{% endblock %}

CMplay/MyMusic/templates/MyMusic/listas.html
<!-- cargar los patch a su staticos
-->
<title>
    CMPlaylist-Listas
</title>

{% extends 'MyMusic/plantilla.html' %}
{% block listas_active %}active{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="center-block">
                <ul class="nav text-center" style="margin-bottom: 10px;">
                    <li role="presentation" ><a> <h2 style="font-family: 'Kaushan Script', cursive; text-transform: uppercase;">{{ username }}</h2> </a></li>

                </ul>

            </div>
            {% if listas %}
                <h3 class="text-center " id="str1" style="text-transform: uppercase">Listas de Reproduccíon</h3>

                {% for lista in listas %}
                    <div class="col-sm-6 col-lg-4">
                        <div class="thumbnail">

                            <div class="caption">
                                <a href="{% url 'MyMusic:lista_detallada' lista.id %}">
                                    <h2 style="text-transform: capitalize" class="bg-info text-center">{{ lista.titulo_de_lista }}</h2>
                                </a>

                                <dl>
                                    {% for cancion in lista.canciones.all %}
                                       <dd> <h4 style="text-transform: capitalize">-{{ cancion.titulo_cancion}}</h4></dd>
                                    {% endfor %}
                                </dl>
                                 <!-- Delete Cancion -->
                                <form action="{% url 'MyMusic:eliminar_lista' lista.id %}" method="post" style="display: inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="cancion_id" value="{{ lista.id }}" />
                                    <abbr title="Eliminar lista">
                                        <button type="submit" class="btn btn-default btn-sm">
                                            <span class="glyphicon glyphicon-trash"></span>
                                        </button>
                                    </abbr>
                                </form>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                 <div class="panel-heading">
                     <h3>No tienes listas de reproducción</h3>
                </div>
            {% endif %}
            {% if  canciones %}
                <div class="col-sm-12">
                    <br>
                    <a href="{% url 'MyMusic:lista-add' %}">
                        <button type="button" class="btn btn-success">
                            <span class="glyphicon glyphicon-plus"></span>&nbsp; Crear Nueva lista
                        </button>
                    </a>
                </div>
            {% else %}
                 <div class="panel-heading">
                     <h3> Para crear listas una debes tener canciones registradas</h3>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

CMplay/MyMusic/templates/MyMusic/login_form.html
<title>
    Django-Play
</title>
{% extends 'MyMusic/plantilla_inicio.html' %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="col-md-19">
        <div class="col-sm-6 col-sm-offset-2">
            <h3 class="col-sm-offset-2"> Iniciar Sesión</h3>
            {% if error_message %}
                <div class="col-sm-13">
                    <p class="col-sm-13" style="color: red "><strong>{{ error_message }}</strong></p>
                </div>

            {% endif %}
            <form method="POST" action="{% url 'MyMusic:login_user' %}" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label class="control-label col-sm-2" for="id_username">
                        Username:
                    </label>
                    <div class="col-sm-13">
                        <input id="id_username" maxlength="30" name="username" type="text">
                    </div>
                   </div>
                <div class="form-group">
                    <label class="control-label col-sm-2" for="id_password">
                        Password:
                    </label>
                    <p></p>
                    <div class="col-sm-13">
                        <input id="id_password" maxlength="30" name="password" type="password">
                    </div>
                </div>

              <h3 class="col-sm-offset-2"> <input type="submit" class="btn btn-info" value=" Iniciar Sesión "></h3>
            </form>
                 <div class="panel-heading">
                     <a href="{% url 'MyMusic:register' %}">Click aquí</a> para crear una cuenta.
                </div>

        </div>
    </div>
</div>
{% endblock %}

CMplay/MyMusic/templates/MyMusic/plantilla.html
<!DOCTYPE html>
<html lang="en">
<head>
{% include 'MyMusic/librarys.html' %}
</head>
<body>

    <nav class="navbar navbar-default">
        <div class="container-fluid">

            <!-- Logo-->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar">  </span>
                </button>
                <a class="navbar-brand" href="{% url 'MyMusic:index' %}"> <strong > Inicio  </strong>   </a>

            </div>

            <!-- item -->
            <div class="collapse navbar-collapse" id="topNavBar" >
                <ul class="nav navbar-nav">
                    <li class="{% block canciones_active %}{% endblock %}">
                        <a href="{% url 'MyMusic:index' %}">
                            <span class="glyphicon glyphicon-music"  aria-hidden="true">  </span> &nbsp; <strong > Canciones  </strong>
                        </a>
                    </li>
                    <li class="{% block listas_active %}{% endblock %}">
                        <a href="{% url 'MyMusic:listas' %}">
                            <span class="glyphicon glyphicon-headphones"  aria-hidden="true">  </span> &nbsp;<strong > Listas de reproducción </strong>
                        </a>
                    </li>
                </ul>
                </ul>

    <!--         -->
                <form class="navbar-form navbar-left"  role="search" method="get" action="{% url 'MyMusic:index' %}">
                    <div class="form-group">
                        <input type="text" class="form-control"  name="q" value="">
                    </div>
                    <button type="submit" class="btn btn-default glyphicon glyphicon-search"> Buscar</button>
                </form>

                <ul class="nav navbar-nav navbar-right">
                    <li class="{% block addcancion_active %}{% endblock %}">
                        <a href="{% url 'MyMusic:cancion-add' %}">
                            <span class="glyphicon glyphicon-plus"  aria-hidden="true">  </span> &nbsp;<strong > Addicionar Cancion</strong>
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'MyMusic:logout_user' %}">
                            <span class="glyphicon glyphicon-log-out"  aria-hidden="true">  </span> &nbsp;<strong > Cerrar Sesión </strong>
                        </a>
                    </li>
                </ul>

            </div>
        </div>
    </nav>
{% block body %}

{% endblock %}
</body>
</html>